spring:
  datasource:
    url: jdbc:mysql://database:3306/spacedb?createDatabaseIfNotExist=true
    username: mars
    password: m4rs
    platform: mysql
    initialization-mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: create

management:
  endpoint:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: space-app.log
    path: /home/vscarmena/dev/metrics/space-app
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  output:
    ansi:
      enabled: DETECT
  level:
    com.vscarmena.space.app: DEBUG
    org.springframework.web: INFO